// Mocks generated by Mockito 5.4.6 from annotations
// in movie_shelf/test/features/scanner/barcode_resolver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_shelf/core/database/app_database.dart' as _i7;
import 'package:movie_shelf/core/network/network_info.dart' as _i10;
import 'package:movie_shelf/core/network/tmdb/tmdb_api_client.dart' as _i9;
import 'package:movie_shelf/core/network/tmdb/tmdb_models.dart' as _i3;
import 'package:movie_shelf/core/network/upcitemdb/upcitemdb_client.dart'
    as _i8;
import 'package:movie_shelf/core/network/upcitemdb/upcitemdb_models.dart'
    as _i2;
import 'package:movie_shelf/features/scanner/data/barcode_repository.dart'
    as _i4;
import 'package:movie_shelf/shared/models/movie.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUpcLookupResult_0 extends _i1.SmartFake
    implements _i2.UpcLookupResult {
  _FakeUpcLookupResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbMovieDetails_1 extends _i1.SmartFake
    implements _i3.TmdbMovieDetails {
  _FakeTmdbMovieDetails_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbCollectionDetails_2 extends _i1.SmartFake
    implements _i3.TmdbCollectionDetails {
  _FakeTmdbCollectionDetails_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbTvDetails_3 extends _i1.SmartFake implements _i3.TmdbTvDetails {
  _FakeTmdbTvDetails_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BarcodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodeRepository extends _i1.Mock implements _i4.BarcodeRepository {
  MockBarcodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Movie?> resolveMovie(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#resolveMovie, [barcode]),
            returnValue: _i5.Future<_i6.Movie?>.value(),
          )
          as _i5.Future<_i6.Movie?>);

  @override
  _i5.Stream<List<_i7.BarcodeRow>> watchBarcodesForMovie(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBarcodesForMovie, [movieId]),
            returnValue: _i5.Stream<List<_i7.BarcodeRow>>.empty(),
          )
          as _i5.Stream<List<_i7.BarcodeRow>>);

  @override
  _i5.Future<void> saveMapping({
    required String? barcode,
    required String? barcodeType,
    required int? movieId,
    String? productTitle,
    String? editionName,
    bool? allowRemap = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMapping, [], {
              #barcode: barcode,
              #barcodeType: barcodeType,
              #movieId: movieId,
              #productTitle: productTitle,
              #editionName: editionName,
              #allowRemap: allowRemap,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveEditionMapping({
    required String? barcode,
    required String? barcodeType,
    required int? physicalEditionId,
    int? movieId,
    String? productTitle,
    String? editionName,
    bool? allowRemap = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditionMapping, [], {
              #barcode: barcode,
              #barcodeType: barcodeType,
              #physicalEditionId: physicalEditionId,
              #movieId: movieId,
              #productTitle: productTitle,
              #editionName: editionName,
              #allowRemap: allowRemap,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMapping(int? barcodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMapping, [barcodeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [BarcodeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodeProvider extends _i1.Mock implements _i8.BarcodeProvider {
  MockBarcodeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UpcLookupResult> lookup(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#lookup, [barcode]),
            returnValue: _i5.Future<_i2.UpcLookupResult>.value(
              _FakeUpcLookupResult_0(
                this,
                Invocation.method(#lookup, [barcode]),
              ),
            ),
          )
          as _i5.Future<_i2.UpcLookupResult>);
}

/// A class which mocks [TmdbApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTmdbApiClient extends _i1.Mock implements _i9.TmdbApiClient {
  MockTmdbApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TmdbSearchResult>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbSearchResult>>.value(
              <_i3.TmdbSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbSearchResult>>);

  @override
  _i5.Future<_i3.TmdbMovieDetails> getMovieDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [tmdbId]),
            returnValue: _i5.Future<_i3.TmdbMovieDetails>.value(
              _FakeTmdbMovieDetails_1(
                this,
                Invocation.method(#getMovieDetails, [tmdbId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbMovieDetails>);

  @override
  _i5.Future<_i3.TmdbCollectionDetails> getCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, [collectionId]),
            returnValue: _i5.Future<_i3.TmdbCollectionDetails>.value(
              _FakeTmdbCollectionDetails_2(
                this,
                Invocation.method(#getCollection, [collectionId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbCollectionDetails>);

  @override
  _i5.Future<List<_i3.TmdbCollectionSearchResult>> searchCollections(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchCollections, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbCollectionSearchResult>>.value(
              <_i3.TmdbCollectionSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbCollectionSearchResult>>);

  @override
  _i5.Future<List<_i3.TmdbTvSearchResult>> searchTv(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbTvSearchResult>>.value(
              <_i3.TmdbTvSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbTvSearchResult>>);

  @override
  _i5.Future<_i3.TmdbTvDetails> getTvDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetails, [tmdbId]),
            returnValue: _i5.Future<_i3.TmdbTvDetails>.value(
              _FakeTmdbTvDetails_3(
                this,
                Invocation.method(#getTvDetails, [tmdbId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbTvDetails>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i10.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
