// Mocks generated by Mockito 5.4.6 from annotations
// in movie_shelf/test/features/import/import_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_shelf/core/network/tmdb/tmdb_api_client.dart' as _i8;
import 'package:movie_shelf/core/network/tmdb/tmdb_models.dart' as _i2;
import 'package:movie_shelf/features/editions/data/physical_edition_repository.dart'
    as _i13;
import 'package:movie_shelf/features/movies/data/movie_repository.dart' as _i4;
import 'package:movie_shelf/features/tv/data/tv_repository.dart' as _i6;
import 'package:movie_shelf/shared/models/collection_status.dart' as _i10;
import 'package:movie_shelf/shared/models/movie.dart' as _i3;
import 'package:movie_shelf/shared/models/physical_edition.dart' as _i7;
import 'package:movie_shelf/shared/models/physical_edition_kind.dart' as _i14;
import 'package:movie_shelf/shared/models/tv_season.dart' as _i12;
import 'package:movie_shelf/shared/models/tv_series.dart' as _i11;
import 'package:movie_shelf/shared/models/tv_series_with_seasons.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTmdbMovieDetails_0 extends _i1.SmartFake
    implements _i2.TmdbMovieDetails {
  _FakeTmdbMovieDetails_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbCollectionDetails_1 extends _i1.SmartFake
    implements _i2.TmdbCollectionDetails {
  _FakeTmdbCollectionDetails_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbTvDetails_2 extends _i1.SmartFake implements _i2.TmdbTvDetails {
  _FakeTmdbTvDetails_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovie_3 extends _i1.SmartFake implements _i3.Movie {
  _FakeMovie_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieUpsertResult_4 extends _i1.SmartFake
    implements _i4.MovieUpsertResult {
  _FakeMovieUpsertResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesWithSeasons_5 extends _i1.SmartFake
    implements _i5.TvSeriesWithSeasons {
  _FakeTvSeriesWithSeasons_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvUpsertResult_6 extends _i1.SmartFake
    implements _i6.TvUpsertResult {
  _FakeTvUpsertResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePhysicalEditionContents_7 extends _i1.SmartFake
    implements _i7.PhysicalEditionContents {
  _FakePhysicalEditionContents_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TmdbApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTmdbApiClient extends _i1.Mock implements _i8.TmdbApiClient {
  MockTmdbApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i2.TmdbSearchResult>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query], {#page: page}),
            returnValue: _i9.Future<List<_i2.TmdbSearchResult>>.value(
              <_i2.TmdbSearchResult>[],
            ),
          )
          as _i9.Future<List<_i2.TmdbSearchResult>>);

  @override
  _i9.Future<_i2.TmdbMovieDetails> getMovieDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [tmdbId]),
            returnValue: _i9.Future<_i2.TmdbMovieDetails>.value(
              _FakeTmdbMovieDetails_0(
                this,
                Invocation.method(#getMovieDetails, [tmdbId]),
              ),
            ),
          )
          as _i9.Future<_i2.TmdbMovieDetails>);

  @override
  _i9.Future<_i2.TmdbCollectionDetails> getCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, [collectionId]),
            returnValue: _i9.Future<_i2.TmdbCollectionDetails>.value(
              _FakeTmdbCollectionDetails_1(
                this,
                Invocation.method(#getCollection, [collectionId]),
              ),
            ),
          )
          as _i9.Future<_i2.TmdbCollectionDetails>);

  @override
  _i9.Future<List<_i2.TmdbCollectionSearchResult>> searchCollections(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchCollections, [query], {#page: page}),
            returnValue: _i9.Future<List<_i2.TmdbCollectionSearchResult>>.value(
              <_i2.TmdbCollectionSearchResult>[],
            ),
          )
          as _i9.Future<List<_i2.TmdbCollectionSearchResult>>);

  @override
  _i9.Future<List<_i2.TmdbTvSearchResult>> searchTv(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query], {#page: page}),
            returnValue: _i9.Future<List<_i2.TmdbTvSearchResult>>.value(
              <_i2.TmdbTvSearchResult>[],
            ),
          )
          as _i9.Future<List<_i2.TmdbTvSearchResult>>);

  @override
  _i9.Future<_i2.TmdbTvDetails> getTvDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetails, [tmdbId]),
            returnValue: _i9.Future<_i2.TmdbTvDetails>.value(
              _FakeTmdbTvDetails_2(
                this,
                Invocation.method(#getTvDetails, [tmdbId]),
              ),
            ),
          )
          as _i9.Future<_i2.TmdbTvDetails>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i4.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i3.Movie>> watchAllMovies() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllMovies, []),
            returnValue: _i9.Stream<List<_i3.Movie>>.empty(),
          )
          as _i9.Stream<List<_i3.Movie>>);

  @override
  _i9.Stream<_i3.Movie?> watchMovie(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchMovie, [id]),
            returnValue: _i9.Stream<_i3.Movie?>.empty(),
          )
          as _i9.Stream<_i3.Movie?>);

  @override
  _i9.Future<_i3.Movie?> getMovieByTmdbId(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieByTmdbId, [tmdbId]),
            returnValue: _i9.Future<_i3.Movie?>.value(),
          )
          as _i9.Future<_i3.Movie?>);

  @override
  _i9.Future<_i3.Movie> addFromTmdb(
    int? tmdbId, {
    required _i10.CollectionStatus? status,
    bool? syncCollection = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFromTmdb,
              [tmdbId],
              {#status: status, #syncCollection: syncCollection},
            ),
            returnValue: _i9.Future<_i3.Movie>.value(
              _FakeMovie_3(
                this,
                Invocation.method(
                  #addFromTmdb,
                  [tmdbId],
                  {#status: status, #syncCollection: syncCollection},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.Movie>);

  @override
  _i9.Future<_i4.MovieUpsertResult> upsertFromDetails(
    _i2.TmdbMovieDetails? details, {
    required _i10.CollectionStatus? status,
    bool? syncCollection = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromDetails,
              [details],
              {#status: status, #syncCollection: syncCollection},
            ),
            returnValue: _i9.Future<_i4.MovieUpsertResult>.value(
              _FakeMovieUpsertResult_4(
                this,
                Invocation.method(
                  #upsertFromDetails,
                  [details],
                  {#status: status, #syncCollection: syncCollection},
                ),
              ),
            ),
          )
          as _i9.Future<_i4.MovieUpsertResult>);

  @override
  _i9.Future<_i4.MovieUpsertResult> applyImportedStatus(
    _i3.Movie? existing,
    _i10.CollectionStatus? incoming,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyImportedStatus, [existing, incoming]),
            returnValue: _i9.Future<_i4.MovieUpsertResult>.value(
              _FakeMovieUpsertResult_4(
                this,
                Invocation.method(#applyImportedStatus, [existing, incoming]),
              ),
            ),
          )
          as _i9.Future<_i4.MovieUpsertResult>);

  @override
  _i9.Future<void> updateStatus(int? movieId, _i10.CollectionStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [movieId, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.Movie> refreshMetadata(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshMetadata, [movieId]),
            returnValue: _i9.Future<_i3.Movie>.value(
              _FakeMovie_3(
                this,
                Invocation.method(#refreshMetadata, [movieId]),
              ),
            ),
          )
          as _i9.Future<_i3.Movie>);

  @override
  _i9.Future<void> deleteMovie(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMovie, [movieId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  bool isMetadataStale(_i3.Movie? movie) =>
      (super.noSuchMethod(
            Invocation.method(#isMetadataStale, [movie]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i6.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i5.TvSeriesWithSeasons>> watchAllSeries() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSeries, []),
            returnValue: _i9.Stream<List<_i5.TvSeriesWithSeasons>>.empty(),
          )
          as _i9.Stream<List<_i5.TvSeriesWithSeasons>>);

  @override
  _i9.Stream<_i5.TvSeriesWithSeasons?> watchSeries(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchSeries, [id]),
            returnValue: _i9.Stream<_i5.TvSeriesWithSeasons?>.empty(),
          )
          as _i9.Stream<_i5.TvSeriesWithSeasons?>);

  @override
  _i9.Future<_i5.TvSeriesWithSeasons?> getSeriesWithSeasonsByTmdbId(
    int? tmdbId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeriesWithSeasonsByTmdbId, [tmdbId]),
            returnValue: _i9.Future<_i5.TvSeriesWithSeasons?>.value(),
          )
          as _i9.Future<_i5.TvSeriesWithSeasons?>);

  @override
  _i9.Future<_i11.TvSeries?> getSeriesByTmdbId(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getSeriesByTmdbId, [tmdbId]),
            returnValue: _i9.Future<_i11.TvSeries?>.value(),
          )
          as _i9.Future<_i11.TvSeries?>);

  @override
  _i9.Future<_i12.TvSeason?> getSeasonByTmdb(
    int? tmdbSeriesId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonByTmdb, [tmdbSeriesId, seasonNumber]),
            returnValue: _i9.Future<_i12.TvSeason?>.value(),
          )
          as _i9.Future<_i12.TvSeason?>);

  @override
  _i9.Future<_i5.TvSeriesWithSeasons> addOrUpdateFromTmdb(
    int? tmdbId, {
    Map<int, _i10.CollectionStatus>? seasonStatuses = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addOrUpdateFromTmdb,
              [tmdbId],
              {#seasonStatuses: seasonStatuses},
            ),
            returnValue: _i9.Future<_i5.TvSeriesWithSeasons>.value(
              _FakeTvSeriesWithSeasons_5(
                this,
                Invocation.method(
                  #addOrUpdateFromTmdb,
                  [tmdbId],
                  {#seasonStatuses: seasonStatuses},
                ),
              ),
            ),
          )
          as _i9.Future<_i5.TvSeriesWithSeasons>);

  @override
  _i9.Future<_i6.TvUpsertResult> upsertFromDetails(
    _i2.TmdbTvDetails? details, {
    Map<int, _i10.CollectionStatus>? seasonStatuses = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromDetails,
              [details],
              {#seasonStatuses: seasonStatuses},
            ),
            returnValue: _i9.Future<_i6.TvUpsertResult>.value(
              _FakeTvUpsertResult_6(
                this,
                Invocation.method(
                  #upsertFromDetails,
                  [details],
                  {#seasonStatuses: seasonStatuses},
                ),
              ),
            ),
          )
          as _i9.Future<_i6.TvUpsertResult>);

  @override
  _i9.Future<void> setSeasonStatus(
    int? seasonId,
    _i10.CollectionStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setSeasonStatus, [seasonId, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setRegularSeasonsStatus(
    int? seriesId,
    _i10.CollectionStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRegularSeasonsStatus, [seriesId, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [PhysicalEditionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhysicalEditionRepository extends _i1.Mock
    implements _i13.PhysicalEditionRepository {
  MockPhysicalEditionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.PhysicalEditionContents> createEdition({
    required _i14.PhysicalEditionKind? kind,
    String? productTitle,
    String? editionName,
    int? tmdbCollectionId,
    int? tmdbTvSeriesId,
    List<int>? movieIds = const [],
    List<int>? seasonIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEdition, [], {
              #kind: kind,
              #productTitle: productTitle,
              #editionName: editionName,
              #tmdbCollectionId: tmdbCollectionId,
              #tmdbTvSeriesId: tmdbTvSeriesId,
              #movieIds: movieIds,
              #seasonIds: seasonIds,
            }),
            returnValue: _i9.Future<_i7.PhysicalEditionContents>.value(
              _FakePhysicalEditionContents_7(
                this,
                Invocation.method(#createEdition, [], {
                  #kind: kind,
                  #productTitle: productTitle,
                  #editionName: editionName,
                  #tmdbCollectionId: tmdbCollectionId,
                  #tmdbTvSeriesId: tmdbTvSeriesId,
                  #movieIds: movieIds,
                  #seasonIds: seasonIds,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.PhysicalEditionContents>);

  @override
  _i9.Future<_i7.PhysicalEditionContents?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i7.PhysicalEditionContents?>.value(),
          )
          as _i9.Future<_i7.PhysicalEditionContents?>);

  @override
  _i9.Future<_i7.PhysicalEditionContents?> getByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getByBarcode, [barcode]),
            returnValue: _i9.Future<_i7.PhysicalEditionContents?>.value(),
          )
          as _i9.Future<_i7.PhysicalEditionContents?>);
}
