// Mocks generated by Mockito 5.4.6 from annotations
// in movie_shelf/test/features/import/import_movie_search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_shelf/core/network/tmdb/tmdb_api_client.dart' as _i7;
import 'package:movie_shelf/core/network/tmdb/tmdb_models.dart' as _i3;
import 'package:movie_shelf/features/import/data/import_repository.dart' as _i4;
import 'package:movie_shelf/features/import/domain/import_models.dart' as _i2;
import 'package:movie_shelf/shared/models/collection_status.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImportCommitReport_0 extends _i1.SmartFake
    implements _i2.ImportCommitReport {
  _FakeImportCommitReport_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbMovieDetails_1 extends _i1.SmartFake
    implements _i3.TmdbMovieDetails {
  _FakeTmdbMovieDetails_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbCollectionDetails_2 extends _i1.SmartFake
    implements _i3.TmdbCollectionDetails {
  _FakeTmdbCollectionDetails_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTmdbTvDetails_3 extends _i1.SmartFake implements _i3.TmdbTvDetails {
  _FakeTmdbTvDetails_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportRepository extends _i1.Mock implements _i4.ImportRepository {
  MockImportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ImportRow>> buildRows(List<String>? rawLines) =>
      (super.noSuchMethod(
            Invocation.method(#buildRows, [rawLines]),
            returnValue: _i5.Future<List<_i2.ImportRow>>.value(
              <_i2.ImportRow>[],
            ),
          )
          as _i5.Future<List<_i2.ImportRow>>);

  @override
  _i5.Future<_i2.ImportCommitReport> commit(
    List<_i2.ImportRow>? rows,
    _i6.CollectionStatus? defaultStatus, {
    void Function(_i2.ImportSaveProgress)? onProgress,
    Set<int>? onlyIndexes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #commit,
              [rows, defaultStatus],
              {#onProgress: onProgress, #onlyIndexes: onlyIndexes},
            ),
            returnValue: _i5.Future<_i2.ImportCommitReport>.value(
              _FakeImportCommitReport_0(
                this,
                Invocation.method(
                  #commit,
                  [rows, defaultStatus],
                  {#onProgress: onProgress, #onlyIndexes: onlyIndexes},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ImportCommitReport>);
}

/// A class which mocks [TmdbApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTmdbApiClient extends _i1.Mock implements _i7.TmdbApiClient {
  MockTmdbApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TmdbSearchResult>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbSearchResult>>.value(
              <_i3.TmdbSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbSearchResult>>);

  @override
  _i5.Future<_i3.TmdbMovieDetails> getMovieDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [tmdbId]),
            returnValue: _i5.Future<_i3.TmdbMovieDetails>.value(
              _FakeTmdbMovieDetails_1(
                this,
                Invocation.method(#getMovieDetails, [tmdbId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbMovieDetails>);

  @override
  _i5.Future<_i3.TmdbCollectionDetails> getCollection(int? collectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, [collectionId]),
            returnValue: _i5.Future<_i3.TmdbCollectionDetails>.value(
              _FakeTmdbCollectionDetails_2(
                this,
                Invocation.method(#getCollection, [collectionId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbCollectionDetails>);

  @override
  _i5.Future<List<_i3.TmdbCollectionSearchResult>> searchCollections(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchCollections, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbCollectionSearchResult>>.value(
              <_i3.TmdbCollectionSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbCollectionSearchResult>>);

  @override
  _i5.Future<List<_i3.TmdbTvSearchResult>> searchTv(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query], {#page: page}),
            returnValue: _i5.Future<List<_i3.TmdbTvSearchResult>>.value(
              <_i3.TmdbTvSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.TmdbTvSearchResult>>);

  @override
  _i5.Future<_i3.TmdbTvDetails> getTvDetails(int? tmdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetails, [tmdbId]),
            returnValue: _i5.Future<_i3.TmdbTvDetails>.value(
              _FakeTmdbTvDetails_3(
                this,
                Invocation.method(#getTvDetails, [tmdbId]),
              ),
            ),
          )
          as _i5.Future<_i3.TmdbTvDetails>);
}
